---

- name: check java version
  shell: "java -version 2>&1"
  register: ver
  ignore_errors: yes
  changed_when: no

- include: install.yml
  when: ver|failed or ver.stdout.find('{{ java_version }}') == -1
