---
- name: create extra groups
  group: state=present name={{ item }}
  with_items: system_groups
  tags: accounts

- name: create user accounts
  user: state=present name={{ item.user }} 
        comment='{{ item.full_name }}'
        home=/home/{{ item.user }}
        shell={{ item.shell | default('/bin/bash') }}
        update_password=always password={{ item.password_crypt }} 
        append=yes groups={{ item.extra_groups | join(',') }}
  with_items: active_accounts
  tags: accounts

- name: setup ssh directories
  file: state=directory dest=/home/{{ item.user }}/.ssh 
        owner={{ item.user }} group={{ item.user }}
  with_items: active_accounts
  tags: accounts

- name: create user authorized_keys
  template: src=authorized_keys dest=/home/{{ item.user }}/.ssh/authorized_keys 
            owner={{ item.user }} group={{ item.user }}
  with_items: active_accounts
  tags: accounts

- name: remove inactive user accounts
  user: state=absent force=yes name={{ item }} 
  with_items: inactive_accounts
  tags: accounts
