---
- name: create extra groups
  group: state=present name={{ item }}
  with_items: admin_groups
  tags: accounts

- name: create user accounts
  user: state=present name={{ item.user }} 
        comment='{{ item.full_name }}'
        home=/home/{{ item.user }}
        shell={{ item.shell | default('/bin/bash') }}
        update_password=always password={{ item.password_crypt }} 
        append=yes groups={{ item.extra_groups | join(',') }}
  with_items: active_accounts
  tags: accounts

- name: setup authorized keys
  authorized_key: key={{ item.ssh_pubkey }} user={{ item.user }} state=present
  with_items: active_accounts
  tags: accounts

- name: remove inactive user accounts
  user: state=absent force=yes name={{ item }} 
  with_items: inactive_accounts
  tags: accounts
