---

# Ubuntu-specific tasks
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# CentOS-specific tasks
- include: centos.yml
  when: ansible_distribution == 'CentOS'

# System-wide configuration
- include: accounts.yml
- include: packages.yml

# /etc/sudoers
- name: setup sudoers file
  template: src=sudoers dest=/etc/sudoers
            owner=root group=root mode=440

# /etc/ssh/sshd_config
- name: setup sshd config file
  template: src=sshd_config dest=/etc/ssh/sshd_config
            owner=root group=root mode=644
  notify:
    - restart centos ssh
    - restart ubuntu ssh
